//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPham_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaBan
    {
        public string ID_GB { get; set; }
        public string ID_SP { get; set; }
        public Nullable<int> Gia_KM { get; set; }
        public Nullable<System.DateTime> TG_BD { get; set; }
        public Nullable<System.DateTime> TG_KT { get; set; }
    }
}
