//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPham_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string ID_HoaDon { get; set; }
        public string ID_ChiTiet { get; set; }
        public Nullable<System.DateTime> Thoi_Gian { get; set; }
    }
}
