//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPham_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public string ID_KH { get; set; }
        public string Ten_KH { get; set; }
        public string Email { get; set; }
        public string Sdt { get; set; }
        public string Dia_Chi { get; set; }
    }
}
