//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPham_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiSP
    {
        public string ID_Loai { get; set; }
        public string ID_Cha { get; set; }
        public string Ten_Loai { get; set; }
        public string MoTa { get; set; }
    }
}
