//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPham_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public string ID_SP { get; set; }
        public string ID_Loai { get; set; }
        public string Ten_SP { get; set; }
        public string HinhAnh { get; set; }
        public string ThuongHieu { get; set; }
        public Nullable<int> So_Luong { get; set; }
        public string Mota { get; set; }
        public string NoiDung { get; set; }
    }
}
